name: Rebase Stable Branch

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: feature-default-anime-instance-checkbox-release

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote (thempc/overseerr)
        run: |
          git remote add upstream https://github.com/thempc/overseerr.git

      - name: Fetch upstream changes
        run: |
          git fetch upstream

      - name: Rebase onto upstream develop
        run: |
          git rebase upstream/develop || {
            echo "Rebase failed. Resetting to previous state..."
            git rebase --abort
            exit 1
          }

      - name: Push rebased branch
        run: |
          git push origin feature-default-anime-instance-checkbox-release --force
